<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXsxxktx\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXsxxktx/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerXsxxktx.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerXsxxktx\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerXsxxktx\appProdProjectContainer([
    'container.build_hash' => 'Xsxxktx',
    'container.build_id' => '36abf104',
    'container.build_time' => 1694100044,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXsxxktx');
